#############################################################################
# Makefile for building: lpub.app/Contents/MacOS/lpub
# Generated by qmake (2.01a) (Qt 4.3.4) on: Tue Apr 15 18:40:31 2008
# Project:  lpub.pro
# Template: app
# Command: /Users/kclague/Downloads/qt-mac-opensource-src-4.3.4/bin/qmake -macx -o Makefile lpub.pro
#############################################################################

####### Compiler, tools and options

CC            = cc
CXX           = c++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.3.4/mkspecs/macx-g++ -I. -I/usr/local/Trolltech/Qt-4.3.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.3.4/include/QtCore -I/usr/local/Trolltech/Qt-4.3.4/include/QtCore -I/usr/local/Trolltech/Qt-4.3.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.3.4/include/QtGui -I/usr/local/Trolltech/Qt-4.3.4/include/QtGui -I/usr/local/Trolltech/Qt-4.3.4/include -I. -I. -I. -F/usr/local/Trolltech/Qt-4.3.4/lib
LINK          = c++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/usr/local/Trolltech/Qt-4.3.4/lib -L/usr/local/Trolltech/Qt-4.3.4/lib -framework QtGui -L/usr/local/Trolltech/Qt-4.3.4/lib -F/usr/local/Trolltech/Qt-4.3.4/lib -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/kclague/Downloads/qt-mac-opensource-src-4.3.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = assemglobals.cpp \
		backgrounddialog.cpp \
		backgrounditem.cpp \
		borderdialog.cpp \
		callout.cpp \
		calloutbackgrounditem.cpp \
		calloutglobals.cpp \
		color.cpp \
		commands.cpp \
		commonmenus.cpp \
		csiitem.cpp \
		dependencies.cpp \
		dividerdialog.cpp \
		editwindow.cpp \
		formatpage.cpp \
		highlighter.cpp \
		ldrawfiles.cpp \
		lpub.cpp \
		main.cpp \
		meta.cpp \
		metagui.cpp \
		metaitem.cpp \
		multistepglobals.cpp \
		numberitem.cpp \
		pagebackgrounditem.cpp \
		pageglobals.cpp \
		pairdialog.cpp \
		partslist.cpp \
		paths.cpp \
		placement.cpp \
		placementdialog.cpp \
		pli.cpp \
		pliconstraindialog.cpp \
		pliglobals.cpp \
		pointeritem.cpp \
		projectglobals.cpp \
		range.cpp \
		range_element.cpp \
		ranges.cpp \
		ranges_element.cpp \
		ranges_item.cpp \
		render.cpp \
		resolution.cpp \
		rotate.cpp \
		rx.cpp \
		scaledialog.cpp \
		step.cpp \
		traverse.cpp moc_backgrounddialog.cpp \
		moc_borderdialog.cpp \
		moc_dividerdialog.cpp \
		moc_editwindow.cpp \
		moc_globals.cpp \
		moc_highlighter.cpp \
		moc_lpub.cpp \
		moc_metagui.cpp \
		moc_pairdialog.cpp \
		moc_placement.cpp \
		moc_placementdialog.cpp \
		moc_pliconstraindialog.cpp \
		moc_scaledialog.cpp \
		qrc_lpub.cpp
OBJECTS       = assemglobals.o \
		backgrounddialog.o \
		backgrounditem.o \
		borderdialog.o \
		callout.o \
		calloutbackgrounditem.o \
		calloutglobals.o \
		color.o \
		commands.o \
		commonmenus.o \
		csiitem.o \
		dependencies.o \
		dividerdialog.o \
		editwindow.o \
		formatpage.o \
		highlighter.o \
		ldrawfiles.o \
		lpub.o \
		main.o \
		meta.o \
		metagui.o \
		metaitem.o \
		multistepglobals.o \
		numberitem.o \
		pagebackgrounditem.o \
		pageglobals.o \
		pairdialog.o \
		partslist.o \
		paths.o \
		placement.o \
		placementdialog.o \
		pli.o \
		pliconstraindialog.o \
		pliglobals.o \
		pointeritem.o \
		projectglobals.o \
		range.o \
		range_element.o \
		ranges.o \
		ranges_element.o \
		ranges_item.o \
		render.o \
		resolution.o \
		rotate.o \
		rx.o \
		scaledialog.o \
		step.o \
		traverse.o \
		moc_backgrounddialog.o \
		moc_borderdialog.o \
		moc_dividerdialog.o \
		moc_editwindow.o \
		moc_globals.o \
		moc_highlighter.o \
		moc_lpub.o \
		moc_metagui.o \
		moc_pairdialog.o \
		moc_placement.o \
		moc_placementdialog.o \
		moc_pliconstraindialog.o \
		moc_scaledialog.o \
		qrc_lpub.o
DIST          = /usr/local/Trolltech/Qt-4.3.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/lex.prf \
		lpub.pro
QMAKE_TARGET  = lpub
DESTDIR       = 
TARGET        = lpub.app/Contents/MacOS/lpub

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile lpub.app/Contents/PkgInfo lpub.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) lpub.app/Contents/MacOS/ || $(MKDIR) lpub.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lpub.pro  /usr/local/Trolltech/Qt-4.3.4/mkspecs/macx-g++/qmake.conf /usr/local/Trolltech/Qt-4.3.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.3.4/lib/QtGui.framework/QtGui.prl \
		/usr/local/Trolltech/Qt-4.3.4/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -macx -o Makefile lpub.pro
/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/common/mac-g++.conf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.3.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.3.4/lib/QtGui.framework/QtGui.prl:
/usr/local/Trolltech/Qt-4.3.4/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o Makefile lpub.pro

lpub.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) lpub.app/Contents || $(MKDIR) lpub.app/Contents 
	@$(DEL_FILE) lpub.app/Contents/PkgInfo
	@echo "APPL????" >lpub.app/Contents/PkgInfo
lpub.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) lpub.app/Contents || $(MKDIR) lpub.app/Contents 
	@$(DEL_FILE) lpub.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,lpub,g" -e "s,@TYPEINFO@,????,g" /usr/local/Trolltech/Qt-4.3.4/mkspecs/macx-g++/Info.plist.app >lpub.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/lpub1.0.0 || $(MKDIR) .tmp/lpub1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/lpub1.0.0/ && $(COPY_FILE) --parents backgrounddialog.h backgrounditem.h borderdialog.h callout.h calloutbackgrounditem.h color.h commands.h commonmenus.h csiitem.h dependencies.h dividerdialog.h editwindow.h globals.h highlighter.h ldrawfiles.h lpub.h meta.h metagui.h metaitem.h metatypes.h name.h numberitem.h pagebackgrounditem.h pairdialog.h partslist.h paths.h placement.h placementdialog.h pli.h pliconstraindialog.h pointer.h pointeritem.h range.h range_element.h ranges.h ranges_element.h ranges_item.h render.h reserve.h resolution.h rx.h scaledialog.h step.h where.h .tmp/lpub1.0.0/ && $(COPY_FILE) --parents lpub.qrc .tmp/lpub1.0.0/ && $(COPY_FILE) --parents assemglobals.cpp backgrounddialog.cpp backgrounditem.cpp borderdialog.cpp callout.cpp calloutbackgrounditem.cpp calloutglobals.cpp color.cpp commands.cpp commonmenus.cpp csiitem.cpp dependencies.cpp dividerdialog.cpp editwindow.cpp formatpage.cpp highlighter.cpp ldrawfiles.cpp lpub.cpp main.cpp meta.cpp metagui.cpp metaitem.cpp multistepglobals.cpp numberitem.cpp pagebackgrounditem.cpp pageglobals.cpp pairdialog.cpp partslist.cpp paths.cpp placement.cpp placementdialog.cpp pli.cpp pliconstraindialog.cpp pliglobals.cpp pointeritem.cpp projectglobals.cpp range.cpp range_element.cpp ranges.cpp ranges_element.cpp ranges_item.cpp render.cpp resolution.cpp rotate.cpp rx.cpp scaledialog.cpp step.cpp traverse.cpp .tmp/lpub1.0.0/ && (cd `dirname .tmp/lpub1.0.0` && $(TAR) lpub1.0.0.tar lpub1.0.0 && $(COMPRESS) lpub1.0.0.tar) && $(MOVE) `dirname .tmp/lpub1.0.0`/lpub1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/lpub1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r lpub.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_backgrounddialog.cpp moc_borderdialog.cpp moc_dividerdialog.cpp moc_editwindow.cpp moc_globals.cpp moc_highlighter.cpp moc_lpub.cpp moc_metagui.cpp moc_pairdialog.cpp moc_placement.cpp moc_placementdialog.cpp moc_pliconstraindialog.cpp moc_scaledialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_backgrounddialog.cpp moc_borderdialog.cpp moc_dividerdialog.cpp moc_editwindow.cpp moc_globals.cpp moc_highlighter.cpp moc_lpub.cpp moc_metagui.cpp moc_pairdialog.cpp moc_placement.cpp moc_placementdialog.cpp moc_pliconstraindialog.cpp moc_scaledialog.cpp
moc_backgrounddialog.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		backgrounddialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backgrounddialog.h -o moc_backgrounddialog.cpp

moc_borderdialog.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		borderdialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ borderdialog.h -o moc_borderdialog.cpp

moc_dividerdialog.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		dividerdialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ dividerdialog.h -o moc_dividerdialog.cpp

moc_editwindow.cpp: editwindow.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ editwindow.h -o moc_editwindow.cpp

moc_globals.cpp: globals.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ globals.h -o moc_globals.cpp

moc_highlighter.cpp: highlighter.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ highlighter.h -o moc_highlighter.cpp

moc_lpub.cpp: ../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		lpub.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ lpub.h -o moc_lpub.cpp

moc_metagui.cpp: ../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metatypes.h \
		metagui.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ metagui.h -o moc_metagui.cpp

moc_pairdialog.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		pairdialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ pairdialog.h -o moc_pairdialog.cpp

moc_placement.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		placement.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ placement.h -o moc_placement.cpp

moc_placementdialog.cpp: ../../lpub/LPub4/metatypes.h \
		placementdialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ placementdialog.h -o moc_placementdialog.cpp

moc_pliconstraindialog.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		pliconstraindialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ pliconstraindialog.h -o moc_pliconstraindialog.cpp

moc_scaledialog.cpp: ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		scaledialog.h
	/usr/local/Trolltech/Qt-4.3.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ scaledialog.h -o moc_scaledialog.cpp

compiler_rcc_make_all: qrc_lpub.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_lpub.cpp
qrc_lpub.cpp: lpub.qrc \
		images/editredo.png \
		images/fitVisible.png \
		images/open.png \
		images/print.png \
		images/editundo.png \
		images/fitPage.png \
		images/prev.png \
		images/paste.png \
		images/save.png \
		images/next.png \
		images/first.png \
		images/zoomout.png \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/last.png \
		images/fitWidth.png \
		images/actual.png \
		images/zoomin.png
	/usr/local/Trolltech/Qt-4.3.4/bin/rcc -name lpub lpub.qrc -o qrc_lpub.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

assemglobals.o: assemglobals.cpp ../../lpub/LPub4/globals.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o assemglobals.o assemglobals.cpp

backgrounddialog.o: backgrounddialog.cpp ../../lpub/LPub4/backgrounddialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backgrounddialog.o backgrounddialog.cpp

backgrounditem.o: backgrounditem.cpp ../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backgrounditem.o backgrounditem.cpp

borderdialog.o: borderdialog.cpp ../../lpub/LPub4/borderdialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o borderdialog.o borderdialog.cpp

callout.o: callout.cpp ../../lpub/LPub4/callout.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/calloutbackgrounditem.h \
		../../lpub/LPub4/pointer.h \
		../../lpub/LPub4/pointeritem.h \
		../../lpub/LPub4/range.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/placementdialog.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o callout.o callout.cpp

calloutbackgrounditem.o: calloutbackgrounditem.cpp ../../lpub/LPub4/callout.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/calloutbackgrounditem.h \
		../../lpub/LPub4/pointer.h \
		../../lpub/LPub4/pointeritem.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calloutbackgrounditem.o calloutbackgrounditem.cpp

calloutglobals.o: calloutglobals.cpp ../../lpub/LPub4/globals.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h \
		../../lpub/LPub4/metaitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calloutglobals.o calloutglobals.cpp

color.o: color.cpp ../../lpub/LPub4/color.h \
		../../lpub/LPub4/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o color.o color.cpp

commands.o: commands.cpp ../../lpub/LPub4/commands.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commands.o commands.cpp

commonmenus.o: commonmenus.cpp ../../lpub/LPub4/commonmenus.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/resolution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commonmenus.o commonmenus.cpp

csiitem.o: csiitem.cpp ../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/callout.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/csiitem.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o csiitem.o csiitem.cpp

dependencies.o: dependencies.cpp ../../lpub/LPub4/dependencies.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dependencies.o dependencies.cpp

dividerdialog.o: dividerdialog.cpp ../../lpub/LPub4/dividerdialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dividerdialog.o dividerdialog.cpp

editwindow.o: editwindow.cpp ../../lpub/LPub4/editwindow.h \
		../../lpub/LPub4/highlighter.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editwindow.o editwindow.cpp

formatpage.o: formatpage.cpp ../../lpub/LPub4/callout.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/range.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/pagebackgrounditem.h \
		../../lpub/LPub4/csiitem.h \
		../../lpub/LPub4/calloutbackgrounditem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formatpage.o formatpage.cpp

highlighter.o: highlighter.cpp ../../lpub/LPub4/highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highlighter.o highlighter.cpp

ldrawfiles.o: ldrawfiles.cpp ../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ldrawfiles.o ldrawfiles.cpp

lpub.o: lpub.cpp ../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/editwindow.h \
		../../lpub/LPub4/commands.h \
		../../lpub/LPub4/paths.h \
		../../lpub/LPub4/globals.h \
		../../lpub/LPub4/render.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lpub.o lpub.cpp

main.o: main.cpp ../../lpub/LPub4/paths.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

meta.o: meta.cpp ../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meta.o meta.cpp

metagui.o: metagui.cpp ../../lpub/LPub4/metagui.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metagui.o metagui.cpp

metaitem.o: metaitem.cpp ../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/placementdialog.h \
		../../lpub/LPub4/pliconstraindialog.h \
		../../lpub/LPub4/pairdialog.h \
		../../lpub/LPub4/scaledialog.h \
		../../lpub/LPub4/borderdialog.h \
		../../lpub/LPub4/backgrounddialog.h \
		../../lpub/LPub4/dividerdialog.h \
		../../lpub/LPub4/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaitem.o metaitem.cpp

multistepglobals.o: multistepglobals.cpp ../../lpub/LPub4/globals.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h \
		../../lpub/LPub4/metaitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multistepglobals.o multistepglobals.cpp

numberitem.o: numberitem.cpp ../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/placementdialog.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numberitem.o numberitem.cpp

pagebackgrounditem.o: pagebackgrounditem.cpp ../../lpub/LPub4/pagebackgrounditem.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pagebackgrounditem.o pagebackgrounditem.cpp

pageglobals.o: pageglobals.cpp ../../lpub/LPub4/globals.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pageglobals.o pageglobals.cpp

pairdialog.o: pairdialog.cpp ../../lpub/LPub4/pairdialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/backgrounddialog.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pairdialog.o pairdialog.cpp

partslist.o: partslist.cpp ../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partslist.o partslist.cpp

paths.o: paths.cpp ../../lpub/LPub4/paths.h \
		../../lpub/LPub4/name.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paths.o paths.cpp

placement.o: placement.cpp ../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/callout.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/range.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o placement.o placement.cpp

placementdialog.o: placementdialog.cpp ../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/placementdialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/resolution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o placementdialog.o placementdialog.cpp

pli.o: pli.cpp ../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/render.h \
		../../lpub/LPub4/paths.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/placementdialog.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pli.o pli.cpp

pliconstraindialog.o: pliconstraindialog.cpp ../../lpub/LPub4/pliconstraindialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pliconstraindialog.o pliconstraindialog.cpp

pliglobals.o: pliglobals.cpp ../../lpub/LPub4/globals.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h \
		../../lpub/LPub4/metaitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pliglobals.o pliglobals.cpp

pointeritem.o: pointeritem.cpp ../../lpub/LPub4/pointeritem.h \
		../../lpub/LPub4/pointer.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pointeritem.o pointeritem.cpp

projectglobals.o: projectglobals.cpp ../../lpub/LPub4/globals.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectglobals.o projectglobals.cpp

range.o: range.cpp ../../lpub/LPub4/range.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/reserve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o range.o range.cpp

range_element.o: range_element.cpp ../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/range_element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o range_element.o range_element.cpp

ranges.o: ranges.cpp ../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ranges_item.h \
		../../lpub/LPub4/range.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/callout.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/calloutbackgrounditem.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/dividerdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ranges.o ranges.cpp

ranges_element.o: ranges_element.cpp ../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ranges_element.o ranges_element.cpp

ranges_item.o: ranges_item.cpp ../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ranges_item.h \
		../../lpub/LPub4/range.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/commonmenus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ranges_item.o ranges_item.cpp

render.o: render.cpp ../../lpub/LPub4/render.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/paths.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o render.o render.cpp

resolution.o: resolution.cpp ../../lpub/LPub4/resolution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resolution.o resolution.cpp

rotate.o: rotate.cpp ../../lpub/LPub4/render.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotate.o rotate.cpp

rx.o: rx.cpp ../../lpub/LPub4/rx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rx.o rx.cpp

scaledialog.o: scaledialog.cpp ../../lpub/LPub4/scaledialog.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/metagui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scaledialog.o scaledialog.cpp

step.o: step.cpp ../../lpub/LPub4/step.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/render.h \
		../../lpub/LPub4/callout.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/calloutbackgrounditem.h \
		../../lpub/LPub4/pointer.h \
		../../lpub/LPub4/pointeritem.h \
		../../lpub/LPub4/csiitem.h \
		../../lpub/LPub4/dependencies.h \
		../../lpub/LPub4/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o step.o step.cpp

traverse.o: traverse.cpp ../../lpub/LPub4/lpub.h \
		../../lpub/LPub4/color.h \
		../../lpub/LPub4/partslist.h \
		../../lpub/LPub4/ranges.h \
		../../lpub/LPub4/pli.h \
		../../lpub/LPub4/meta.h \
		../../lpub/LPub4/where.h \
		../../lpub/LPub4/metatypes.h \
		../../lpub/LPub4/resolution.h \
		../../lpub/LPub4/placement.h \
		../../lpub/LPub4/backgrounditem.h \
		../../lpub/LPub4/metaitem.h \
		../../lpub/LPub4/name.h \
		../../lpub/LPub4/ldrawfiles.h \
		../../lpub/LPub4/rx.h \
		../../lpub/LPub4/callout.h \
		../../lpub/LPub4/numberitem.h \
		../../lpub/LPub4/pointer.h \
		../../lpub/LPub4/range.h \
		../../lpub/LPub4/ranges_element.h \
		../../lpub/LPub4/reserve.h \
		../../lpub/LPub4/range_element.h \
		../../lpub/LPub4/step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o traverse.o traverse.cpp

moc_backgrounddialog.o: moc_backgrounddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backgrounddialog.o moc_backgrounddialog.cpp

moc_borderdialog.o: moc_borderdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_borderdialog.o moc_borderdialog.cpp

moc_dividerdialog.o: moc_dividerdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dividerdialog.o moc_dividerdialog.cpp

moc_editwindow.o: moc_editwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editwindow.o moc_editwindow.cpp

moc_globals.o: moc_globals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_globals.o moc_globals.cpp

moc_highlighter.o: moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highlighter.o moc_highlighter.cpp

moc_lpub.o: moc_lpub.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lpub.o moc_lpub.cpp

moc_metagui.o: moc_metagui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_metagui.o moc_metagui.cpp

moc_pairdialog.o: moc_pairdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pairdialog.o moc_pairdialog.cpp

moc_placement.o: moc_placement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_placement.o moc_placement.cpp

moc_placementdialog.o: moc_placementdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_placementdialog.o moc_placementdialog.cpp

moc_pliconstraindialog.o: moc_pliconstraindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pliconstraindialog.o moc_pliconstraindialog.cpp

moc_scaledialog.o: moc_scaledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scaledialog.o moc_scaledialog.cpp

qrc_lpub.o: qrc_lpub.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_lpub.o qrc_lpub.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

